# Generated by Django 5.1.6 on 2025-03-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0002_map_layer_rectangle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='map',
            new_name='pinmap',
        ),
    ]
