# Generated by Django 5.1.6 on 2025-03-05 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0003_rename_map_layer_pinmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
