# Generated by Django 5.1.6 on 2025-03-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0004_alter_map_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='lat',
            field=models.FloatField(default=52.520008),
        ),
        migrations.AddField(
            model_name='map',
            name='lng',
            field=models.FloatField(default=13.404954),
        ),
        migrations.AddField(
            model_name='map',
            name='zoom',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='map',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
