# Generated by Django 5.1.6 on 2025-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0005_map_lat_map_lng_map_zoom_alter_map_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_default',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='Default', max_length=50),
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
