# Generated by Django 5.1.6 on 2025-03-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0006_map_is_default_map_name_alter_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='pinmap',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pinmap.map'),
            preserve_default=False,
        ),
    ]
