# Generated by Django 5.1.6 on 2025-03-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0008_alter_layer_name_alter_map_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='map',
            name='is_default',
        ),
    ]
