# Generated by Django 5.1.6 on 2025-03-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0009_remove_layer_is_default_remove_map_is_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('owner', 'pinmap', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together={('owner', 'name')},
        ),
    ]
