# Generated by Django 5.2 on 2025-04-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinmap', '0010_alter_layer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
    ]
